//
// account actions
//
export const LOGIN_USER = 'LOGIN_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const CONFIRM_TOKEN = 'CONFIRM_TOKEN';
export const LOG_OUT = 'LOG_OUT';
//
// auth actions
//
export const RESET_AUTH = 'RESET_AUTH';
export const RESET_CODE_ERROR = 'RESET_CODE_ERROR';
export const AXIOS_PHONE_BEGIN = 'AXIOS_PHONE_BEGIN';
export const AXIOS_PHONE_SUCCESS = 'AXIOS_PHONE_SUCCESS';
export const AXIOS_PHONE_FAILURE = 'AXIOS_PHONE_FAILURE';
export const AXIOS_CODE_BEGIN = 'AXIOS_CODE_BEGIN';
export const AXIOS_CODE_SUCCESS = 'AXIOS_CODE_SUCCESS';
export const AXIOS_CODE_FAILURE = 'AXIOS_CODE_FAILURE';
//
// university actions
//
export const UNIVERSITY_LOADING_SUCCESS = 'UNIVERSITY_LOADING_SUCCESS';
export const UNIVERSITY_LOADING_BEGIN = 'UNIVERSITY_LOADING_BEGIN';
export const UNIVERSITY_LOADING_FAILURE = 'UNIVERSITY_LOADING_FAILURE';
//
// cities actions
//
export const SELECT_CITY = 'SELECT_CITY';
export const CITIES_LOADING_BEGIN = 'CITIES_LOADING_BEGIN';
export const CITIES_LOADING_SUCCESS = 'CITIES_LOADING_SUCCESS';
export const CITIES_LOADING_FAILURE = 'CITIES_LOADING_FAILURE';
//
// blog posts actions
//
export const POSTS_LOADING_BEGIN = 'POSTS_LOADING_BEGIN';
export const POSTS_LOADING_SUCCESS = 'POSTS_LOADING_SUCCESS';
export const POSTS_LOADING_FAILURE = 'POSTS_LOADING_FAILURE';
//
// modal action
//
export const HANDLE_MODAL = 'HANDLE_MODAL';
//
// university actions -> ratings
//
export const UNIVERSITY_RATING_POST_BEGIN = 'UNIVERSITY_RATING_POST_BEGIN';
export const UNIVERSITY_RATING_POST_SUCCESS = 'UNIVERSITY_RATING_POST_SUCCESS';
export const UNIVERSITY_RATING_POST_FAILURE = 'UNIVERSITY_RATING_POST_FAILURE';
export const UNIVERSITY_RATING_EDIT_BEGIN = 'UNIVERSITY_RATING_EDIT_BEGIN';
export const UNIVERSITY_RATING_EDIT_SUCCESS = 'UNIVERSITY_RATING_EDIT_SUCCESS';
export const UNIVERSITY_RATING_EDIT_FAILURE = 'UNIVERSITY_RATING_EDIT_FAILURE';
export const UNIVERSITY_RATING_DELETE_BEGIN = 'UNIVERSITY_RATING_DELETE_BEGIN';
export const UNIVERSITY_RATING_DELETE_SUCCESS = 'UNIVERSITY_RATING_DELETE_SUCCESS';
export const UNIVERSITY_RATING_DELETE_FAILURE = 'UNIVERSITY_RATING_DELETE_FAILURE';
//
// professor actions
//
export const PROFESSOR_LOADING_SUCCESS = 'PROFESSOR_LOADING_SUCCESS';
export const PROFESSOR_LOADING_BEGIN = 'PROFESSOR_LOADING_BEGIN';
export const PROFESSOR_LOADING_FAILURE = 'PROFESSOR_LOADING_FAILURE';
//
// professor actions -> ratings
//
export const PROFESSOR_RATING_POST_BEGIN = 'PROFESSOR_RATING_POST_BEGIN';
export const PROFESSOR_RATING_POST_SUCCESS = 'PROFESSOR_RATING_POST_SUCCESS';
export const PROFESSOR_RATING_POST_FAILURE = 'PROFESSOR_RATING_POST_FAILURE';
export const PROFESSOR_RATING_EDIT_BEGIN = 'PROFESSOR_RATING_EDIT_BEGIN';
export const PROFESSOR_RATING_EDIT_SUCCESS = 'PROFESSOR_RATING_EDIT_SUCCESS';
export const PROFESSOR_RATING_EDIT_FAILURE = 'PROFESSOR_RATING_EDIT_FAILURE';
export const PROFESSOR_RATING_DELETE_BEGIN = 'PROFESSOR_RATING_DELETE_BEGIN';
export const PROFESSOR_RATING_DELETE_SUCCESS = 'PROFESSOR_RATING_DELETE_SUCCESS';
export const PROFESSOR_RATING_DELETE_FAILURE = 'PROFESSOR_RATING_DELETE_FAILURE';
//
// error actions
//
export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';
//
// routing actions
//
export const ROUTE_SET_LAST_LOCATION = 'ROUTE_SET_LAST_LOCATION';
//
// theme actions
//
export const THEME_SET_DARK = 'THEME_SET_DARK';
export const THEME_SET_LIGHT = 'THEME_SET_LIGHT';
